on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features --all-targets

  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings

  test:
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest, target: i686-unknown-linux-gnu, use-cross: true, cmd: --no-default-features --features server }
          - { os: ubuntu-latest, target: i686-unknown-linux-musl, use-cross: true, cmd: --no-default-features --features server }
          - { os: ubuntu-latest, target: x86_64-unknown-linux-musl, use-cross: true, cmd: --no-default-features --features server }
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu, cmd: --no-default-features --features server }
          - { os: macos-latest, target: x86_64-apple-darwin, cmd: --no-default-features --features server }
          - { os: macos-latest, target: aarch64-apple-darwin, cmd: --no-default-features --features server }
          - { os: windows-latest, target: i686-pc-windows-msvc, cmd: --no-default-features --features server }
          - { os: windows-latest, target: x86_64-pc-windows-gnu, cmd: --no-default-features --features server }
          - { os: windows-latest, target: x86_64-pc-windows-msvc, cmd: --no-default-features --features server }
    name: Test ${{ matrix.job.os }} (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.job.target }}
      - uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: test
          args: --target=${{ matrix.job.target }} ${{ matrix.job.cmd }}
